import { Injectable } from "@nestjs/common";
import { PrismaService } from "../prisma.service";
import { createInstallationToken } from "./github.service";

interface CommitResult {
  prUrl: string;
  prNumber: number;
  branch: string;
  committed: string[];
}

interface CommitError {
  error: string;
  detail?: string;
}

interface ArtifactDiffFile {
  path: string;
  status: "new" | "changed" | "unchanged";
  additions: number;
  deletions: number;
  hunks: Array<{ type: "context" | "add" | "remove"; content: string; lineNumber?: number }>;
}

const SKIP_KINDS = new Set(["cloudformation_role"]);
const COMMIT_MESSAGE = "chore(awsify): add generated deployment files";
const PR_TITLE = "AWS-ify: generated deployment files";
const PR_BODY_LINES = [
  "This PR adds the deployment files generated by AWS-ify for this project.",
  "",
  "- `Dockerfile` — container build for the service",
  "- `.github/workflows/*.yml` — CI workflow that triggers AWS-ify on push",
  "- Pulumi preview files — record of the planned AWS resources",
  "",
  "Review the diff, then merge to enable repeatable deploys from your CI."
];

@Injectable()
export class GithubCommitService {
  constructor(private readonly prisma: PrismaService) {}

  async getDeploymentArtifactDiff(
    deploymentId: string,
    userId: string
  ): Promise<{ files: ArtifactDiffFile[]; branch: string } | CommitError> {
    const deployment = await this.prisma.deployment.findUnique({
      where: { id: deploymentId },
      include: {
        project: {
          include: {
            repository: { include: { installation: true } }
          }
        },
        plan: { include: { artifacts: true } }
      }
    });

    if (!deployment) return { error: "deployment_not_found" };
    if (deployment.project.userId !== userId) return { error: "not_authorized" };

    const repo = deployment.project.repository;
    const installation = repo.installation;
    const [owner, repoName] = repo.fullName.split("/");
    if (!owner || !repoName) return { error: "invalid_repo_fullname" };

    let token: string;
    try {
      token = await createInstallationToken(installation.installationId);
    } catch (err) {
      return { error: "installation_token_failed", detail: errorMessage(err) };
    }

    const branch = deployment.project.branch || repo.defaultBranch;
    const files: ArtifactDiffFile[] = [];
    for (const artifact of deployment.plan.artifacts.filter((a) => !SKIP_KINDS.has(a.kind))) {
      const existing = await getFileContent(token, owner, repoName, artifact.path, branch);
      if (existing.error && existing.error !== "not_found") {
        return { error: "file_lookup_failed", detail: `${artifact.path}: ${existing.error}` };
      }
      files.push(createLineDiff(artifact.path, existing.content ?? "", artifact.content, existing.error === "not_found"));
    }

    return { files, branch };
  }

  async commitDeploymentArtifacts(deploymentId: string, userId: string): Promise<CommitResult | CommitError> {
    const deployment = await this.prisma.deployment.findUnique({
      where: { id: deploymentId },
      include: {
        project: {
          include: {
            repository: { include: { installation: true } }
          }
        },
        plan: { include: { artifacts: true } }
      }
    });

    if (!deployment) return { error: "deployment_not_found" };
    if (deployment.project.userId !== userId) return { error: "not_authorized" };

    const repo = deployment.project.repository;
    const installation = repo.installation;
    if (!installation) return { error: "installation_missing" };

    const artifacts = deployment.plan.artifacts.filter((a) => !SKIP_KINDS.has(a.kind));
    if (artifacts.length === 0) return { error: "no_artifacts" };

    const [owner, repoName] = repo.fullName.split("/");
    if (!owner || !repoName) return { error: "invalid_repo_fullname" };

    let token: string;
    try {
      token = await createInstallationToken(installation.installationId);
    } catch (err) {
      return { error: "installation_token_failed", detail: errorMessage(err) };
    }

    const baseBranch = repo.defaultBranch;
    const newBranch = `awsify/deploy-${deployment.id.slice(0, 8)}`;

    const baseSha = await getBranchHeadSha(token, owner, repoName, baseBranch);
    if (!baseSha) return { error: "base_branch_lookup_failed", detail: `Could not read ${baseBranch}` };

    const branchResult = await ensureBranch(token, owner, repoName, newBranch, baseSha);
    if (branchResult.error) return { error: "branch_create_failed", detail: branchResult.error };

    const committed: string[] = [];
    for (const artifact of artifacts) {
      const existingSha = await getFileSha(token, owner, repoName, artifact.path, newBranch);
      const put = await putFile(token, owner, repoName, artifact.path, newBranch, artifact.content, existingSha);
      if (!put.ok) {
        return { error: "file_commit_failed", detail: `${artifact.path}: ${put.error}` };
      }
      committed.push(artifact.path);
    }

    const pr = await openPullRequest(token, owner, repoName, newBranch, baseBranch);
    if ("error" in pr) return { error: "pr_create_failed", detail: pr.error };

    return {
      prUrl: pr.html_url,
      prNumber: pr.number,
      branch: newBranch,
      committed
    };
  }
}

function createLineDiff(path: string, before: string, after: string, isNew: boolean): ArtifactDiffFile {
  const beforeLines = before.split(/\r?\n/);
  const afterLines = after.split(/\r?\n/);
  const max = Math.max(beforeLines.length, afterLines.length);
  const hunks: ArtifactDiffFile["hunks"] = [];
  let additions = 0;
  let deletions = 0;

  for (let i = 0; i < max; i += 1) {
    const oldLine = beforeLines[i];
    const newLine = afterLines[i];
    if (oldLine === newLine) {
      if (hunks.length < 120 && oldLine !== undefined) hunks.push({ type: "context", content: oldLine, lineNumber: i + 1 });
      continue;
    }
    if (oldLine !== undefined && !(i === beforeLines.length - 1 && oldLine === "" && newLine === undefined)) {
      deletions += 1;
      if (hunks.length < 120) hunks.push({ type: "remove", content: oldLine, lineNumber: i + 1 });
    }
    if (newLine !== undefined && !(i === afterLines.length - 1 && newLine === "" && oldLine === undefined)) {
      additions += 1;
      if (hunks.length < 120) hunks.push({ type: "add", content: newLine, lineNumber: i + 1 });
    }
  }

  return {
    path,
    status: isNew ? "new" : additions === 0 && deletions === 0 ? "unchanged" : "changed",
    additions,
    deletions,
    hunks
  };
}

interface GitHubRefResponse {
  object?: { sha: string };
  message?: string;
}

interface GitHubContentItem {
  sha?: string;
  message?: string;
}

interface GitHubPullResponse {
  number: number;
  html_url: string;
  message?: string;
  errors?: Array<{ message?: string }>;
}

async function getBranchHeadSha(token: string, owner: string, repo: string, branch: string): Promise<string | null> {
  const res = await fetch(`https://api.github.com/repos/${owner}/${repo}/git/ref/heads/${encodeURIComponent(branch)}`, {
    headers: ghHeaders(token)
  });
  if (!res.ok) return null;
  const data = (await res.json()) as GitHubRefResponse;
  return data.object?.sha ?? null;
}

async function ensureBranch(
  token: string,
  owner: string,
  repo: string,
  branch: string,
  baseSha: string
): Promise<{ error?: string }> {
  const existing = await fetch(`https://api.github.com/repos/${owner}/${repo}/git/ref/heads/${encodeURIComponent(branch)}`, {
    headers: ghHeaders(token)
  });
  if (existing.ok) return {};

  const res = await fetch(`https://api.github.com/repos/${owner}/${repo}/git/refs`, {
    method: "POST",
    headers: ghHeaders(token),
    body: JSON.stringify({ ref: `refs/heads/${branch}`, sha: baseSha })
  });
  if (res.ok) return {};
  const data = (await res.json().catch(() => ({}))) as GitHubRefResponse;
  return { error: data.message ?? `HTTP ${res.status}` };
}

async function getFileSha(
  token: string,
  owner: string,
  repo: string,
  path: string,
  branch: string
): Promise<string | undefined> {
  const res = await fetch(
    `https://api.github.com/repos/${owner}/${repo}/contents/${encodePath(path)}?ref=${encodeURIComponent(branch)}`,
    { headers: ghHeaders(token) }
  );
  if (!res.ok) return undefined;
  const data = (await res.json()) as GitHubContentItem;
  return data.sha;
}

async function getFileContent(
  token: string,
  owner: string,
  repo: string,
  path: string,
  branch: string
): Promise<{ content?: string; error?: string }> {
  const res = await fetch(
    `https://api.github.com/repos/${owner}/${repo}/contents/${encodePath(path)}?ref=${encodeURIComponent(branch)}`,
    { headers: ghHeaders(token) }
  );
  if (res.status === 404) return { error: "not_found" };
  const data = (await res.json().catch(() => ({}))) as GitHubContentItem & { content?: string; encoding?: string };
  if (!res.ok) return { error: data.message ?? `HTTP ${res.status}` };
  if (!data.content || data.encoding !== "base64") return { error: "unsupported_content_encoding" };
  return { content: Buffer.from(data.content.replace(/\n/g, ""), "base64").toString("utf8") };
}

async function putFile(
  token: string,
  owner: string,
  repo: string,
  path: string,
  branch: string,
  content: string,
  sha: string | undefined
): Promise<{ ok: boolean; error?: string }> {
  const res = await fetch(`https://api.github.com/repos/${owner}/${repo}/contents/${encodePath(path)}`, {
    method: "PUT",
    headers: ghHeaders(token),
    body: JSON.stringify({
      message: COMMIT_MESSAGE,
      content: Buffer.from(content, "utf8").toString("base64"),
      branch,
      ...(sha ? { sha } : {})
    })
  });
  if (res.ok) return { ok: true };
  const data = (await res.json().catch(() => ({}))) as GitHubContentItem;
  return { ok: false, error: data.message ?? `HTTP ${res.status}` };
}

async function openPullRequest(
  token: string,
  owner: string,
  repo: string,
  head: string,
  base: string
): Promise<GitHubPullResponse | { error: string }> {
  const res = await fetch(`https://api.github.com/repos/${owner}/${repo}/pulls`, {
    method: "POST",
    headers: ghHeaders(token),
    body: JSON.stringify({
      title: PR_TITLE,
      head,
      base,
      body: PR_BODY_LINES.join("\n")
    })
  });
  const data = (await res.json().catch(() => ({}))) as GitHubPullResponse;
  if (res.ok && data.number && data.html_url) return data;

  if (data.errors?.[0]?.message?.includes("A pull request already exists")) {
    const existing = await findExistingPr(token, owner, repo, head, base);
    if (existing) return existing;
  }
  return { error: data.message ?? `HTTP ${res.status}` };
}

async function findExistingPr(
  token: string,
  owner: string,
  repo: string,
  head: string,
  base: string
): Promise<GitHubPullResponse | null> {
  const res = await fetch(
    `https://api.github.com/repos/${owner}/${repo}/pulls?head=${owner}:${encodeURIComponent(head)}&base=${encodeURIComponent(base)}&state=open`,
    { headers: ghHeaders(token) }
  );
  if (!res.ok) return null;
  const list = (await res.json()) as GitHubPullResponse[];
  return list[0] ?? null;
}

function ghHeaders(token: string) {
  return {
    Authorization: `Bearer ${token}`,
    Accept: "application/vnd.github+json",
    "Content-Type": "application/json",
    "X-GitHub-Api-Version": "2022-11-28"
  };
}

function encodePath(path: string): string {
  return path.split("/").map(encodeURIComponent).join("/");
}

function errorMessage(err: unknown): string {
  return err instanceof Error ? err.message : String(err);
}
