import { Injectable } from "@nestjs/common";
import { createDeploymentPlan } from "@awsify/templates";
import type { DeploymentPlan, DeploymentSuggestion } from "@awsify/deployment-schemas";
import { QueueService } from "../queue/queue.service";

@Injectable()
export class DeploymentsService {
  private readonly plans = new Map<string, DeploymentPlan>();

  constructor(private readonly queue: QueueService) {}

  createPlan(input: { projectId: string; appName: string; region: string; repoFullName: string; branch: string }) {
    const suggestion: DeploymentSuggestion = {
      appType: input.repoFullName.includes("next") ? "nextjs-app" : "node-backend",
      services: input.repoFullName.includes("next") ? ["frontend"] : ["backend"],
      packageManager: "npm",
      buildCommand: "npm run build",
      startCommand: "npm start",
      installCommand: "npm ci",
      port: 3000,
      hasDockerfile: false,
      envVars: [],
      database: { required: false },
      confidence: 0.5,
      notes: ["Mock plan generated by API. Worker scan replaces this in the connected-repo flow."]
    };

    const plan = createDeploymentPlan({
      projectId: input.projectId,
      appName: input.appName,
      region: input.region,
      awsifyAccountId: process.env.AWSIFY_AWS_ACCOUNT_ID ?? "123456789012",
      externalId: `awsify-${input.projectId}`,
      suggestion
    });

    this.plans.set(plan.id, plan);
    return { plan };
  }

  approvePlan(id: string) {
    const plan = this.plans.get(id);
    if (!plan) return { status: "not_found" };
    const approved = { ...plan, status: "approved" as const };
    this.plans.set(id, approved);
    return { plan: approved };
  }

  async deployApprovedPlan(
    approvedPlanId: string,
    input: { projectId: string; repoFullName: string; branch: string; awsConnectionId: string; actorUserId: string }
  ) {
    const plan = this.plans.get(approvedPlanId);
    if (!plan || plan.status !== "approved") return { status: "not_approved" };

    const job = await this.queue.enqueueDeployment({
      projectId: input.projectId,
      repoFullName: input.repoFullName,
      branch: input.branch,
      awsConnectionId: input.awsConnectionId,
      approvedPlanId,
      actorUserId: input.actorUserId
    });

    return { status: "queued", jobId: job.id };
  }
}
